BEGIN;

DROP EXTENSION IF EXISTS pg_trgm;
DROP TABLE IF EXISTS ban_history;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS relations;
DROP TABLE IF EXISTS bookmarks;
DROP TABLE IF EXISTS tagged_posts;
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS users;
DROP TYPE hub_enum;

COMMIT;